version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 80:8081
    volumes:
      - .:/var/www/app

  #sc_composer:
  #  image: vaguesoftware/sidecar-composer:latest
  #  volumes:
  #    - .:/var/www/app

  rabbit:
    image: rabbitmq:3-management
    volumes:
      - ./var/rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672